# Generated by Django 5.2.1 on 2025-07-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='advt_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='date_of_publication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('MPSC', 'MPSC'), ('UPSC', 'UPSC')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='sr_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
